<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SymfonyStandard' => array($baseDir . '/app'),
    '' => array($baseDir . '/src'),
);
