<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'JShrink' => array($vendorDir . '/tedivm/jshrink/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
    'CoffeeScript' => array($vendorDir . '/coffeescript/coffeescript/src'),
    '' => array($vendorDir),
);
